- lib/ios/LottieReactNative.xcodeproj/project.pbxproj
`../../node_modules` is only work for example.
Also, I can't found `Lottie.framework` if I just use `react-native link` without CocoaPods, so it still not work, could we have a download link for that?
> [iOS] Fix header search paths 

- README.md
- example/ios/Podfile
- example/ios/Podfile.lock
- example/ios/example.xcodeproj/project.pbxproj
- lib/ios/LottieReactNative/LottieAnimationViewManager.h
- lib/ios/LottieReactNative/LottieAnimationViewManager.m
- lib/ios/LottieReactNative/LottieContainerView.h
- lib/ios/LottieReactNative/LottieContainerView.m
- lib/js/Animation.js
- package.json
Fixes #25 
Fixes #20 
Closes #18 
Closes #23 
I've tested these changes with RN 0.41 as well as RN 0.38 and I believe it's backwards compatible.
The only limitation is that with RN >= 0.40, this will not work with CocoaPods + `use_frameworks!`, which as far as I can tell is a community-wide issue with RN 0.40+ right now, and probably won't be fixed until RN 0.42.
> Fix build issues

- lib/ios/LottieReactNative.xcodeproj/project.pbxproj
- lib/ios/LottieReactNative/LRNAnimationViewManager.h
- lib/ios/LottieReactNative/LRNAnimationViewManager.m
- lib/ios/LottieReactNative/LRNContainerView.h
- lib/ios/LottieReactNative/LRNContainerView.m
3 letters prefixes are the standard for iOS classes, LRN for Lottie React Native.
This doesn't change the native module name so no breaking change.
> Change classes prefix to LRN instead of Lottie on iOS

- README.md
This hint comes from @jozan: https://github.com/airbnb/lottie-react-native/issues/59#issuecomment-280082995
> Add embedded framework hint to the README

- lib/js/Animation.js
Using `View.propTypes` is outdated since rn@0.44.
> Upgrade to ViewPropTypes instead of View.PropTypes

- lib/android/src/main/java/com/airbnb/android/react/lottie/JSONReadableArray.java
- lib/android/src/main/java/com/airbnb/android/react/lottie/JSONReadableMap.java
One of our AfterEffect json file was not working properly in lottie-react-native. But was working fine in lottie-react-native. Verified it by placing json in to official examples. 
After spending some time in code, figured out the problem. The problem is `JSONReadableMap.java` and `JSONReadableArray.java` files are converting `Number` type to `Integer` by default and reading as `Double` on exception. This seems to be causing some issues and stripping off decimal values.
```java
@Override
public Object opt(String name) {
switch (map.getType(name)) {
...
case Number:
try {
return map.getInt(name);
} catch (Exception e) {
return map.getDouble(name);
}
...
}
}
```
Got animation working fine by changing the default type to double. 
```java
@Override
public Object opt(String name) {
switch …
```
> Reading all numbers as double from ReadableMap and ReadableArray

- lib/android/build.gradle
Some build tasks need to be able to specify configuration in lottie eg:
compile project(path: ':lottie', configuration: 'release')
To do this, we need to publish these configuration options to the parent projects.
> Publish configuration options

- docs/api.md
- lib/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java
This PR adds support for imageAssetsFolder prop - see [airbnb/lottie-android#image-support](https://github.com/airbnb/lottie-android#image-support).
**Example**
```
<Animation
style={{
width: 200,
height: 200,
}}
source={require('./data.json')}
progress={this.state.progress}
imageAssetsFolder={'lottie/images'}
/>
```
**Tasks**
> [Android] Add imageAssetsFolder prop

- lib/android/src/main/java/com/airbnb/android/react/lottie/LottiePackage.java
[`createJSModules` is now not required on Android](https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8) from RN 0.47. This is backwards compatible according to my tests in comparison to #168.
> Remove createJSModules @override - RN 0.47 compatibility

- example/ExamplePicker.js
- example/PlayerControls.js
- lib/js/Animation.js
- package.json
Because `PropTypes` is not available anymore in newer React packages, we need to use the standalone `prop-types` package to keep using PropTypes functionality.
See https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes
> Use prop-types package (PropTypes in React package is deprecated)

- README.md
- example/LottieAnimatedExample.js
By default, `Animated.timing` uses the `Easing.inOut(Easing.ease)` easing function. This means that animations do not play quite as expected. I think that the majority use case will be for linear easing and should be documented: those unfamiliar with the `Animated` API may not be aware of the default behaviour.
> Use linear easing in examples and docs

- example/LottieAnimatedExample.js
- lib/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java
- lib/js/Animation.js
This should fix https://github.com/airbnb/lottie-react-native/issues/185.
I don't have the warning saying `Animation contains merge paths but they are disabled.` but sadly I tried with an animation with merge paths that is working on iOS and it only rendered a blank space on android.
> Expose a new prop to enable merge paths on android

- docs/api.md
- lib/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java
* Completed the missing `setSpeed` functionality in the ReactNative Android library.
* Added documentation around the usage of `setSpeed` according to the native implementation of `LottieAnimationView`
> Added the functionality of setting the Speed of the Animation for Android

- index.d.ts
This maps the documentation from http://airbnb.io/lottie/react-native/props.html to TypeScript typings, with some additional information provided.
I'm not sure if the "AnimationObject" interface is entirely accurate -- for instance, all those fields are currently marked as required but perhaps they can be optional?
> Create typings file for lottie-react-native

- src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java
- src/js/LottieView.js
- src/js/index.d.ts
Per https://github.com/airbnb/lottie-android/issues/151, hardware acceleration for large animations is often helpful, provided the animation has not been scaled beyond its original dimensions.
> Expose Android's hardwareAcceleration as prop

- package.json
currently those dependencies are being installed in our work modules and create conflicts with eslint versions.
> move eslint packages to devDependencies

- docs/api.md
- example/js/LottieAnimatedExample.js
- src/js/LottieView.js
Hello,
Here is some features from https://github.com/bamlab/easy-lottie-react-native/issues/1, there's everything except:
- automatic duration according to the animation's JSON data (I might do another PR). With the `autoPlay` prop that I added here, it becomes a bit useless (with the imperative API, the correct duration is taken into account)
- the fix for Android animation's JSON data bug, I couldn't reproduce it here, lottie-android must have fixed it already ! 👌
The PR became a bit big along the way, let me know if you want that I break it down :)
- adds automatic aspectRatio according to the animation's JSON data (won't work when the source is a native asset)
- adds `autoSize` prop that will size the prop according to the animation's JSON data (won't work when the source is a native …
> Add features from easy-lottie-react-native

- package.json
- src/js/index.d.ts
This change has a side effect as the typescript code is not going to be identical to the javascript sample because of the way the export works in Javascript.
> Fixed typescript support

- src/ios/LottieReactNative.xcodeproj/project.pbxproj
This pull request adds support for iOS projects that use [Carthage](https://github.com/Carthage/Carthage) for iOS dependencies instead of Cocoapods.
Carthage is used a lot in the iOS community and it would be great to add support for it.
How to test?
1. [Add Lottie to your Cartfile ](http://airbnb.io/lottie/ios.html#installing-lottie)
2. Run `carthage update`
3. Link react native `react-native link lottie-react-native`
> Support Carthage projects

- README.md
A number of developers find it painful to find the docs. This can help them a bit.
> [docs] Point to React Native docs directly

- src/js/index.d.ts
A recent change introduced the `autoPlay` property, but it wasn't added to the typings.
> add autoPlay property to typescript typings

- src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java
This way may cause NPE： `view.setAnimation(new JSONObject(json));`
I think the JSONObject can make json format, so the order changed. And parsing depends on this order。
The NPE log is,
```
E/AndroidRuntime(24975): java.lang.NullPointerException
E/AndroidRuntime(24975):        at com.airbnb.lottie.animation.content.BaseStrokeContent.<init>(BaseStrokeContent.java:63)
E/AndroidRuntime(24975):        at com.airbnb.lottie.animation.content.StrokeContent.<init>(StrokeContent.java:26)
E/AndroidRuntime(24975):        at com.airbnb.lottie.model.content.ShapeStroke.toContent(ShapeStroke.java:77)
E/AndroidRuntime(24975):        at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:30)
E/AndroidRuntime(24975):        at …
```
> make Lottie view use the json string directly

- package.json
- src/ios/LottieReactNative/LRNContainerView.m
Because we're setting the content mode directly on `_animationView` (see commit 89775d9f6e2b7d768771f43b62454c0d154412c3), we need to copy it when the animation view is replaced.
> Preserve content mode when animation view is replaced

- src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java
On Android, sometimes the view would not be attached when the command play was sent - typically with `autoPlay` and when the animation is inside a `ViewPagerAndroid`. Instead of failing silently this makes it so that the command is executed when the view is attached.
> [Android] Wait for the view to be attached when playing (fixes autoplay)

- example/js/ExamplePicker.js
- example/js/LottieAnimatedExample.js
- src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewPropertyManager.java
When controlling animation progress using `Animated.Value` Lottie animation was flickering with Android. Did some investigation and it seems that `animationJson` was parsed and applied every time any property change would happen. Setting animation only once solved that issue.
Also examples seemed to be broken when imperative API was disabled so fixed progress slider and cleaned up some example code.
Probably resolves #362
> Clear animationJson property to resolve Android flickering issues

- package.json
For some reason, different versions of typescript can find the type definition when
the folder is specified, but some compilers and editors (such as vscode) does not like this
Using the specific file instead as I could not find any flow description in here.
> Fixed typescript type publication

- src/android/build.gradle
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
> Remove Gradle warning

- src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewPropertyManager.java
Basically, stopped using view.loop(true or false) to use view.setRepeatCount(INFINITE or 0)
which, can be extended in the future (removing loop for setRepeatCount directly)
> This change removes the deprecation warning received whilst compiling Android

- src/js/index.d.ts
The duration prop was not added to the Typescript types file.
> Update types to add duration property

- src/js/index.d.ts
The js file does not have a default export.
The typescript mechanism for a function or class commonjs `module.exports` is `export =`.
> Use commonjs object export compatible syntax

- lottie-react-native.podspec
- package.json
- yarn.lock
There are compilation errors with 2.5.3 from npmjs repository so we should lock lottie-ios on 2.5.0 until we will migrate to 3.x.x
> Lock lottie-ios on version 2.5.0

- src/js/LottieView.js
Since react-native 0.58.0-rc.0 `react-native-safe-module` is throwing a `missing prop mock` warning defined [here](https://github.com/lelandrichardson/react-native-safe-module/blob/master/src/NativeSafeModule.js#L114) since `getConstants` mock is missing (`getConstants` become a part of native modules API in [this](https://github.com/facebook/react-native/commit/db43aa8fc3dd9ca87d227df0c109a6f5c213f90b) commit).
Require `lottie-react-native` in any project with react-native >= 0.58.0-rc.0
> Resolve missing prop mock warning

- package.json
It could have impact on android build but as we package supports RN 60 it should not make any difference.
- Build android project.
> Remove deprecated `rnpm` configuration.

- docs/api.md
I found on the file `src/js/index.d.ts` the `hardwareAccelerationAndroid` prop. It wasn't described on the API documentation.
> Add doc for hardwareAccelerationAndroid

- react-native.config.js
Related to : #521 
This config makes `autolink` work properly.
I hope this helps.
> Fix crash on Android and RN 0.60

- CHANGELOG.md
- build.gradle
- docs/api.md
- example/android/app/build.gradle
- example/android/app/src/main/AndroidManifest.xml
- example/android/gradle/wrapper/gradle-wrapper.properties
- package.json
- src/android/build.gradle
- src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java
- src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewPropertyManager.java
- src/js/LottieView.js
This PR adds support for Lottie Android 3.0.0
Apps using `lottie-react-native` should still work on android.
| Android |    ✅    |
> support for lottie android 3

- src/ios/LottieReactNative/ContainerView.swift
The method for loading named assets on iOS wasn't actually doing anything. I added a simple implementation using AnimatedView(name:) which does exactly what we want and also takes care of caching the loaded animation.
None
- Add an animation json to your xcode project
- Add a lottie view like: `<LottieView source="nameOfAnimationWithNoExtension" />
N/A
> Fix loading assets from app bundle on iOS

- src/android/build.gradle
This config line is not used and results in a warning when building:
```
> Configure project :lottie-react-native
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
```
Fixes #534
> Remove unused deprecated `publishNonDefault` Gradle option

- src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java
To match the behaviour on iOS this adds a .json extension when not specified. This allow writing the same JS code for iOS and Android when using assets by name.
Tested that passing an asset by name without an extension will work on both iOS and Android.
```js
// This will find a file named `my_animation.json` in `main/assets` on Android and
// `my_animation.json` added to the xcode project on iOS.
<LottieView source="my_animation" />
```
N/A
> Support passing extensionless file names on Android

- src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java
Trying to fix #522 
I'm new to this. My changes to the java classes have no effect when i run it locally with expo. I tried to build with gradle but still no effect. I read the contributing guidelines but was no wiser.
Any help would be appreciated.
> Fix android crash when .play() startFrame > endFrame

- src/ios/LottieReactNative/ContainerView.swift
Fix AnimationUIblock on scroll or when mounting and unmounting components in ios
* What issues does the pull request solve? #412 #560 #530 #496 
* How did you implement the solution?   
`animationView?.backgroundBehavior = .pauseAndRestore` when animation plays inside `ContainerView.swift` file!
Change tabs and scroll like and it should work like as charm!
Scroll lottie inside scrollview or navigate between screens and tabs!
> Fix animation stops when ui block or scroll (iOS)

- CHANGELOG.md
- README.md
- src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java
- src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewPropertyManager.java
- src/ios/LottieReactNative/ContainerView.swift
- src/ios/LottieReactNative/LRNAnimationViewManagerObjC.m
- src/js/index.d.ts
Added support to override color of a layer (solves #180) following [android](http://airbnb.io/lottie/#/android?id=looping) and [ios](http://airbnb.io/lottie/#/ios) documentations.
```javascript
colorFilters={[{
keypath: layer,
color: colorHex
}]}
```
Just install the package and try to override one layer color.
> Add support for color filters by layer

- CHANGELOG.md
- src/ios/LottieReactNative/ContainerView.swift
It will fix #598 by changing the animation speed on setSpeed method on native code. 
It will also play or pause the animation according to the speed.
- Start with an animation speed of 0
- Change it to 1 after a few seconds. The animation should play
- Change it back to 0. The animation should pause
| Android |    ❌     |
> Fix #598. Add new logic to setSpeed

- src/ios/LottieReactNative/AnimationViewManagerModule.swift
Fixing an issue that in newer version of lottie-react-native isCanceled having wrong value and a different value than the android
* What areas of the library does it impact?
the ios version of the library
-->
- run any lottie animation using the library and add onAnimationFinish callback and log the isCancelled parameter
- interrupt that animation 
- Android: isCancelled is true while on ios: isCancelled is false
- After change both android and ios will have isCancelled true
> fix: Fixed ios isCancelled in onAnimationFinish getting the wrong value

- lottie-react-native.podspec
Swift 5.0 is commonly used because of ABI stability, and Xcode is asking the project to be migrated to 5.0. Swift 4.2 code require no change, thus compatible with 5.0.
Compiles and works as expected.
| iOS     |    ✅❌     |
| Android |    ✅❌     |
- [ x] I have tested this on a device and a simulator
> use Swift 5.0

- docs/api.md
- src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java
- src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewPropertyManager.java
- src/js/index.d.ts
We currently use `lottie-react-native` , recently we received the report of an error that is occurring with some Lottie's with Android 7 and it is related to Hardware acceleration in Android.
Following this issue in this thread
https://github.com/airbnb/lottie-android/issues/1453
We found that it can be solved with a `renderMode` property that is out of the box inside the `lottie-android` library, but this property is not exposed in React Native, so this PR expose it to be used from React Native
We already tested this and it's works! 🎉 
| iOS     |    ❌     |
> Add renderMode property for Android

- src/js/LottieView.js
After upgrading to lottie-react-native 3.4.0, the following warnings occur.
```
ReactNative.NativeModules.LottieAnimationView.pause did not have a corresponding prop defined in the mock provided to SafeModule.
ReactNative.NativeModules.LottieAnimationView.resume did not have a corresponding prop defined in the mock provided to SafeModule.
```
This fix is intended to eliminate warnings.
> Fix warnings about pause/resume

- src/js/index.d.ts
When using typescript `typecheck` code validation, typescript is pointing it out that the `LayoutChangeEvent` is missing from the react-native imports in the [`index.d.ts`](https://github.com/react-native-community/lottie-react-native/blob/4f4ff693658cc5def04440732a2e1ab9e3e0491c/src/js/index.d.ts) type definition file.
When running: `tsc --noEmit -p .` from the project folder where typescript is set and `lottie-react-native` is installed and being used, the following error occurs:
- node_modules/lottie-react-native/src/js/index.d.ts(126,24): error TS2304: Cannot find name 'LayoutChangeEvent'
> Add missing type from reac-native package

- src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewPropertyManager.java
This PR solves, changing color issue  for child elements in Android 
Normally we can change child elements colors with passing a dot in the keypath in IOS
`
{
keypath: 'Flyer.#Primary Front Arm',
color: '#FFFF00',
}
`
But it is not working for Android because the constructor of KeyPath class needs a java varargs types and in the code, we are directly passing path as a string to KeyPath constructor
In this PR I have split the path variable with the dot and called KeyPath constructor with a string array
`
public KeyPath(String... keys) {
this.keys = Arrays.asList(keys);
}
`
Try to change a child element color with colorFilters in Android
> fix(colorfilter): colorfilter path issue has been fixed for android

- package.json
`lottie-ios` is a project with native code and it has to be linked.
react-native autolinking can only work as long as project is listed in
the output of `react-native config` which considers `package.json` in
order to build list of dependencies which need to be linked.
currently having `lottie-ios` in `dependencies` does not make lots of
sense since in order to successfully install and use
`lottie-react-native` one has to install `lottie-ios` separately and
make sure it's listed in `package.json`.
in fact it may lead to situatoin when two copies of `lottie-ios` may be
installed in case if range of `lottie-ios` inside package.json of
`lottie-react-native` and inside actual package of the app are
conflicting.
> fix: move `lottie-ios` to `peerDependencies`

- src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java
Everytime we played an animation with startFrame > endFrame, we
were reversing the animation speed. As so, it played correctly
for the first time, but incorrectly on the second (as it was
reversed back to the regular animation speed).
Now, we only reverse the animation speed if needed. Additionally
we restore the original animation speed if needed for
startFrame < endFrame.
> Fix Android playback when startFrame > endFrame

- src/ios/LottieReactNative/AnimationViewManagerModule.swift
- src/ios/LottieReactNative/ContainerView.swift
RCT_DEV can be used to enable or disable development tools but RCT_DEBUG can be used to exclude error checking and logging code from release builds. (https://github.com/facebook/react-native/blob/master/React/Base/RCTDefines.h)
RCT_DEV replaced with RCT_DEBUG to disable logging.
> RCT_DEV replaced with RCT_DEBUG

- lottie-react-native.podspec
- src/ios/LottieReactNative/AnimationViewManagerModule.swift
- src/ios/LottieReactNative/ContainerView.swift
* Enables ARC (automatic reference counting)
* Depends on React-Core (fixes Xcode 12 compatibility)
* Removes unnecessary React imports in swift code
* Sets `DEFINES_MODULE` to true (creates header maps, allows React-Core interop)
* Removes `SWIFT_VERSION` pinning
> Fix react-native 0.64 compatibility

- src/js/index.d.ts
It would potentially be useful for people to be able to import the props type separately if needed.  For example, when combining LottieView with a styled component that takes custom props, so the props type can be extended if needed.
> add ability to import props type

- src/ios/LottieReactNative/AnimationViewManagerModule.swift
- src/ios/LottieReactNative/ContainerView.swift
This PR fixes an issue that causes erratic `onAnimationFinish` callbacks on iOS when we call `resume()`. Since the callback was passed in with the call to `play(..., completion: handler)`, and since `resume()` calls `play()` without any arguments, the animation completion callback gets lost if we ever pause the animation. (Note: that's not what's done in the android version), 
Here, we remove callback the references from the iOS manager module. Since `ContainerView` holds the property, we can always pass the callback directly in there.
> Fix `onAnimationFinish` callback behavior after resuming on iOS

- lottie-react-native.podspec
Regarding: https://github.com/onevcat/Kingfisher/issues/1725
"This seems only happens for SPM and it requires a minimum target iOS 12 to build successfully. I don't think this is reasonable and it is definitely an issue of the build system (unless Apple officially confirms they want to drop any deploy target below iOS 12)"
> Build on xcode 13 beta

- build.gradle
- src/android/build.gradle
Upgraded as a first step to migrating to gradle 7. It simply points to the latest native Android version: https://github.com/airbnb/lottie-android/releases/tag/v4.0.0
> Upgrading Native lottie Android to 4.0.0

- src/android/gradle-maven-push.gradle
the `maven` gradle plugin has been deprecated for a while. The replacement is `maven-plugin` that has some changes to the DSL. I have adapted them. I have verified that compilation works but for obvious reasons, I can't publish it myself. 
This migration is necessary in order to move `lottie-react-native-` to use gradle 7.0.0+ used in the latest Android Studio.
This is a dependency to https://github.com/lottie-react-native/lottie-react-native/pull/799 but the change can be merged independently
> migrated to maven_publish

- lottie-react-native.podspec
Fixes this error during RN macOS init:
[!] Unable to determine Swift version for the following pods:  - `lottie-react-native-macOS` does not specify a Swift version and none of the targets (`bluewallet-macOS`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
> Swift Version on Pod spec

- src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewPropertyManager.java
<h3>This pull request fix a error.</h3>
<hr />
* Changing the object type as it is causing android app installation errors.
* Install react latest versions: react 17.0.2, react-native 0.66.3;
* Install lottie-react-native@latest version and it peerDependencies lottie-ios@3.2.3;
* Run ```npx react-native run-android```;
* The error described at #820 will be displayed.
> Fix incompatible types of objects

- docs/api.md
This PR adds the [`resizeMode`](https://github.com/lottie-react-native/lottie-react-native/blob/master/src/js/LottieView.js#L69) prop to the "Component API" docs.
> docs: add `resizeMode` to Component API

- .eslintrc
- package.json
- src/js/LottieView.js
- yarn.lock
React native recently completely removed ViewPropTypes, and static typing is now generally preferred over prop types. This removes prop types.
See https://github.com/facebook/react-native/commit/10199b158138b8645550b5579df87e654213fe42
> Remove PropTypes

- src/android/build.gradle
Seems there have been some memory consumption improvements since v5.0.x of lottie-android. This PR updates the dependency to the latest version. https://github.com/airbnb/lottie-android/releases/tag/v5.0.1
> Upgrade android lottie to 5.0.3

- src/ios/LottieReactNative/ContainerView.swift
If one tries to update colorFilters while the animation is running,
prior to this patch the animation would simple stop running.
This is caused because applyProperties() always sets
animationView.currentProgress, which according to the
docs stops the animation in case it's running.
In order to prevent such scenario the applyProperties()
will check if the animation is running before any updates.
After all props are updated, it will resume the animation in
case it was playing.
https://airbnb.io/lottie/#/ios?id=current-progress
> fix: allow one to change lottie props and keep the animation running

- src/js/index.d.ts
For projects that are using TS AnimationObject is necessary to determine the type of the image/animation.
Exporting it from the source would simplify that since we don't have to duplicate it locally.
> chore(js): export AnimationObject

- src/android/build.gradle
The android lottie team published a new update with some general improvements.
Ref: https://github.com/airbnb/lottie-android/releases/tag/v5.1.1
> Upgrade android lottie to 5.1.1

- src/js/LottieView.js
It seems that older versions of react-native do not load `deprecated-react-native-prop-types`.
```
deprecated-react-native-prop-types could not be found within the project or in these directories:
node_modules/lottie-react-native/node_modules
node_modules
If you are sure the module exists, try these steps:
1. Clear watchman watches: watchman watch-del-all
2. Delete node_modules and run yarn install
3. Reset Metro's cache: yarn start --reset-cache
4. Remove the cache: rm -rf /tmp/metro-*
```
ViewPropType is no longer used in e1f409b and has been removed.
Alternatively, I would like to see `deprecated-react-native-prop-types` added to the dependencies in package.json.
> fix 'deprecated-react-native-prop-types could not be found' error

- src/ios/LottieReactNative/ContainerView.swift
I got the following build error on tvOS after upgrade lottie-react-native to v5:
```
'hasDifferentColorAppearance(comparedTo:)' is only available in tvOS 13.0 or newer
```
This simple fix just add '#available' version check for tvOS.
> Fix UITraitCollection.hasDifferentColorAppearance check for tvOS version less than 13.0

- README.md
This PR should probably only be merged after doing the next release which actually unblocks the usage of the newer lottie-ios version.
> Update readme to use new lottie-ios version

- README.md
- example/ios/Podfile.lock
- example/package.json
- example/yarn.lock
- package.json
Users need to install `lottie-ios` compatible with their `lottie-react-native` version in order to use library.
As we are moving forward, I think it is good to remove peer dependency and depend on podspec to install the proper version from podspec without manually installing `lottie-ios` on the project.  
From now on, `lottie-ios` can be installed and detected automatically from podspec configuration and users do not need to install both of them in order to use it.
> chore: remove lottie-ios peer dependency

- apps/paper/package.json
- yarn.lock
Removing `react-native-windows` for paper example for now due to https://github.com/microsoft/react-native-windows/issues/11093.
> chore: remove react-native-windows for paper example

- apps/paper/package.json
- yarn.lock
Fixed in RNW 0.71.0
Reference: https://github.com/microsoft/react-native-windows/issues/11093
> chore: bring back RNW to paper example

- packages/core/ios/LottieReactNative/ContainerView.swift
This fixes the bug where the animation resets to its first frame when going to background and resume.
Issue: https://github.com/lottie-react-native/lottie-react-native/issues/825
When going to background, `traitCollectionDidChange` method runs which calls `applyProperties()`. This changes the animation's current progress `animationView.currentProgress = progress` and `progress` comes from props. If not defined it defaults to 0 (first frame).
Additionally, setting `backgroundBehavior = .pauseAndRestore` has a weird behavior. When the animation ends and the app goes to background, it sets the animation to the first frame. Forcing the `currentProgress` to the last frame when the animation ends works fine to mitigate the issue.
https://user-images.githubusercontent.com/3791120/215833991-ec57dd …
> fix(iOS): reset to first frame on app resume bug

- README.md
This PR introduces two minor fixes to README:
* Add missing `useRef` import in one code example
* Change example path in another example for consistency
> fix: add missing import and update path in readme

- packages/core/package.json
- yarn.lock
We have added release-it as a development dependency to streamline release management and simplify the patching process.
The use of release-it will make it easier to handle releases and patches without any additional hassle.
To start a release, run the following script:
```bash
yarn workspace lottie-react-native release
```
For pre-release:
```
yarn workspace lottie-react-native release --preRelease=rc --npm.tag=rc
```
For further information, please refer to the official documentation at: https://github.com/release-it/release-it
> chore: add release script

- packages/core/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManagerImpl.kt
- packages/core/android/src/main/java/com/airbnb/android/react/lottie/LottiePackage.kt
- packages/core/android/src/main/java/com/airbnb/android/react/lottie/OnAnimationFinishEvent.kt
- packages/core/android/src/newarch/com/airbnb/android/react/lottie/LottieAnimationViewManager.kt
- packages/core/android/src/oldarch/com/airbnb/android/react/lottie/LottieAnimationViewManager.kt
fixes https://github.com/lottie-react-native/lottie-react-native/issues/963
This PR refactors the event dispatch logic on Android and makes use of the EventDispatcher on paper and fabric. I did a test in both architectures via the example project and was successfully able to see the relevant console log which is running when an animation finishes.
cc @matinzd @alfonsocj @emilioicai
> fix: refactor event dispatch logic on android to fix fabric crash

- apps/fabric/ios/Podfile.lock
- apps/fabric/src/App.tsx
- apps/paper/ios/Podfile.lock
- apps/paper/src/LottieAnimatedExample.tsx
- apps/paper/src/constants.ts
- apps/paper/src/utils.ts
- packages/core/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManagerImpl.kt
- packages/core/src/LottieView.tsx
- packages/core/src/LottieView.types.ts
There are a lot of styles being applied behind the scenes resulting in unexpected behaviors.
Remove the outer layer and pass everything directly to native lottie view
- Removed using Animated API by default in the source code, fixes (#1003)
- Fix resize mode in Android
- Removed absolute style being applied to the `LottieVIew`
- Removed default aspect ratio styling
- Removed default width being applied
You need to handle everything related to aspect ratio and sizing yourself. The reason for removing all these default values is to avoid confusion when using the library as well as to prevent unexpected behaviors.
- https://github.com/lottie-react-native/lottie-react-native/issues/989
- https://github.com/lottie-react-native/lottie-react-native/issues/1003
- …
> BREAKING CHANGE: cleanup lottie component and remove default styles

- packages/core/ios/LottieReactNative/ContainerView.swift
This PR removes the `print("dark mode changed")` from the project.
This screenshot is from my work project where I use lottie.
> chore: remove redundant logging from the project 

- packages/core/ios/LottieReactNative/ContainerView.swift
Fixes: https://github.com/lottie-react-native/lottie-react-native/issues/1018
> fix: react native macos build

- packages/core/ios/LottieReactNative/ContainerView.swift
As per our discussion, This PR does a bunch of refactoring to both:
1. Simplify the logic of `setSourceURL` with a guard
2. Break the reference cycle (only needed for the internal Dispatch back to main because the first one doesn't capture self anyway)
3. Break the reference cycle for the callback
One area we can improve is with moving the call to decode Json in `setSourceJson` to a background thread, but it isn't a memory leak so much as "Kind of a slow op" so not in scope for this PR
I also made the completion callback a computed property so it doesn't recreate a new callback every time, just one, and while there was a small memory improvement, it was minuscule, so i am more than willing to roll it back
Picture of instruments showing a release:
> fix: memory leak issue

- apps/paper/src/LottieAnimatedExample.tsx
- packages/core/android/build.gradle
- packages/core/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManagerImpl.kt
- packages/core/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewPropertyManager.kt
- Fix autoplay bug
- Upgrade android lottie to 6.1.0
- Remove coroutines
> chore: upgrade android lottie to 6.1.0

- apps/paper/src/FramesExample.tsx
- packages/core/ios/LottieReactNative/ContainerView.swift
No need to force the animation to stay on the end frame anymore.
Fixes: https://github.com/lottie-react-native/lottie-react-native/issues/1049
> fix: prevent jumping to end frame while calling play method

- apps/paper/src/LottieAnimatedExample.tsx
- apps/paper/src/RenderModePicker.tsx
- packages/core/src/index.tsx
version 6.0.0 removed the types from lottie. this change should allow them to be imported again
```ts
src/apps/Focus/screens/Landing/index.tsx:1:23 - error TS2614: Module '"lottie-react-native"' has no exported member 'AnimationObject'. Did you mean to use 'import AnimationObject from "lottie-react-native"' instead?
1 import Lottie, { type AnimationObject } from 'lottie-react-native';
~~~~~~~~~~~~~~~
```
> export types from lottie

- packages/core/ios/LottieReactNative/ContainerView.swift
- packages/core/lottie-react-native.podspec
`lottie-react-native-tvOS` does not specify a Swift version and none of the targets ({project_name}) integrating it have the `SWIFT_VERSION` attribute set.
> fix: unable to determine Swift version

- .gitignore
- packages/core/ios/LottieReactNative/ContainerView.swift
In this PR, we are re-adding the usage of the self keyword for iOS, as we are now supporting older Xcode and Swift versions and these features were not available with older versions (Implicit self capture after unwrapping [was introduced in Swift 5.8](https://github.com/apple/swift-evolution/blob/main/proposals/0365-implicit-self-weak-capture.md))
Fixes https://github.com/lottie-react-native/lottie-react-native/issues/1083
> fix: re-add usage of self for older versions of Xcode with lower versions of Swift

- .github/workflows/ios-build.yml
- packages/core/ios/LottieReactNative/ContainerView.swift
Add CI to test against different versions of XCode starting from 13.3.1.
Docs for macos-12 runners: https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
> chore(ci): add ci for ios example build test

- packages/core/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewPropertyManager.kt
It seems that bundler flattens folder structure using underscore for each subfolder, removes the file extension and the full path in release mode.
Fixes: https://github.com/lottie-react-native/lottie-react-native/issues/1090
Reference: https://github.com/facebook/react-native/issues/24963
> fix: dot lottie for android in release mode

- README.md
- docs/api.md
- packages/core/README.md
- Moved dotLottie documentation to main readme file
- Added documentation for `.lottie` file extension in jest environment
Preview: https://github.com/lottie-react-native/lottie-react-native/tree/chore/update_docs
> chore: update dot lottie documentation

- packages/core/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewPropertyManager.kt
#1091 added code that (AFAICT) assumes debug builds will always load from Metro. However, it is possible to build a debuggable app that includes the JS bundle (although probably uncommon). Instead, I propose following the same approach as [ImageSource](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/imagehelper/ImageSource.java#L78) which handles all possible inputs (remote uri, local asset, uri, local asset name, etc).
> chore: check uri scheme instead of BuildConfig.DEBUG

- apps/fabric/ios/Podfile.lock
- apps/fabric/package.json
- apps/paper/ios/Podfile.lock
- apps/paper/package.json
- packages/core/lottie-react-native.podspec
Important fixes in this release:
- Fix issue where shape items could be unexpectedly ignored (https://github.com/airbnb/lottie-ios/pull/2156)
- Fix issue where skew keyframes would unexpectedly not animate (https://github.com/airbnb/lottie-ios/pull/2157)
- Fix issue where value providers could be ignored when falling back to main thread rendering engine (https://github.com/airbnb/lottie-ios/pull/2164)
https://github.com/airbnb/lottie-ios/releases/tag/4.3.0
> chore: bump lottie-ios 4.3.0

- packages/core/src/LottieView/index.web.tsx
The current web implementation requires projects to include both `@lottiefiles/react-lottie-player` and `@dotlottie/react-player` because they are required in the same try/catch block.
Apps should be able to install either of these depending on whether they need to play `.lottie` files or not.
This PR separates the requires into separate try/catch blocks so `@lottiefiles/react-lottie-player` can be installed and used without including `@dotlottie/react-player`.
> fix(web): don't require @dotlottie/react-player to be installed for JSON animations

- packages/core/ios/LottieReactNative/ContainerView.swift
So we can choose to use mainThread or coreAnimation when using text filters.
> fix(ios): missing configuration if textFilters used

- packages/core/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewPropertyManager.kt
Lottie Android v6 includes feature https://github.com/airbnb/lottie-android/pull/2103 so we can use ReactFontManager to get loaded font assets correctly.
For example, https://lottiefiles.com/animations/3d-loop-button-with-text-change-option-mbnBq8lzk2 will caused app crash during error `Font asset not found fonts/Roboto.ttf`.
This PR:
- If found the font, it should displayed text correctly
- It can avoid the app crash with default typeface fallback if font asset not found
I've been using this patch internally from lottie-react-native v5 (it was Java version) some time. It also fix #961.
For iOS, it should be supported by default.
> feat(android): support font assets

- packages/core/ios/LottieReactNative/ContainerView.swift
The frame of the child animation view on iOS is not setup or updated correctly when we first render the element. This has been due to us reading the `bounds` from `RCTView`, which for some reason is reporting incorrect values on the new arch on initial render. This PR switches us over to overriding and calling `layoutSubiews` directly, which lets us correctly set the frame.
I have tested this on both Fabric and on Paper to make sure nothing has broken for any of the implementations
> fix: animation frames being incorrect on new arch for the first frame

- packages/core/ios/Fabric/LottieAnimationViewComponentView.mm
- packages/core/lottie-react-native.podspec
This change updates the `lottie-react-native.podspec` to consume the `install_modules_dependencies` function provided by React Native to configure the pods dependencies.
Thanks to using this function, whenever we update the pods structure in React Native, the library will automatically benefit from it.
This will make the library more future proof and more resilient to changes in React Native.
This allow Lottie to work also with `use_frameworks!` and with the New Architecture. Before the change, it failed to build when `use_frameworks!` was set in RN 0.73.x
Tested locally:
Before changes
1. Created a new app with `npx react-native init RNFrameworks --version
latest --skip-install`
1. `cd RNFrameworks`
1. `yarn add lottie-react-native`
1. `yarn install`
1. `cd ios`
1. `NO_FLIPPER=1 …
> chore(iOS): Use `install_modules_dependencies` in Podspec

- .vscode/settings.json
- apps/fabric/ios/Podfile.lock
- apps/fabric/ios/example/Info.plist
- packages/core/lottie-react-native.podspec
`install_modules_dependencies` is not working as expected with `RCT_NEW_ARCH_ENABLED=1` for some reason. This is a temporary fix for 72 and below to ensure backward compatibility.
> fix(workaround): enable `install_modules_dependencies` just for RN 73 and above

- packages/core/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewPropertyManager.kt
Introduced in https://github.com/lottie-react-native/lottie-react-native/pull/1128, this PR aims to remove the incorrect default that was being set for the type face. The value `400` is not a valid type face, and strictly not required in this context as `getTypeface` always returns a valid type face.
Note for the future: This variant of `ReactFontManager` is now depracated. RN 73 introduces a new package: `com.facebook.react.common.assets.ReactFontManager`. We should consider doing a breaking change at some point to cover both this and the updated podspec build script.
> fix: remove incorrect typeface default

- .github/workflows/android-paper-build.yml
- apps/paper/package.json
- package.json
Add CI build step on Android to lint the Kotlin files before building to ensure stuff like https://github.com/lottie-react-native/lottie-react-native/issues/1150 never happens again
> chore: add linting to paper's build step on Android

- README.md
The LottieView in ReactNative must set the `width` and `height` styles to display properly
> Update README.md: LottieView must set the `width` and `height` styles to display properly

- packages/core/ios/PrivacyInfo.xcprivacy
- packages/core/lottie-react-native.podspec
This PR aims to make us compliant with Apple's upcoming privacy manifest requirements that will go into effect come Spring 2024. We will need to do another update once [Lottie iOS releases 4.4.0](https://github.com/airbnb/lottie-ios/pull/2252#issuecomment-1885925359) with their own privacy manifest as well, but for now, This is all that is required.
I also bumped our Lottie iOS dep to 4.3.4, just so everything is on the latest version
> feat: add privacy manifest for iOS

- .github/workflows/ios-paper-build.yml
- apps/fabric/ios/Podfile.lock
- apps/paper/ios/Podfile.lock
- packages/core/lottie-react-native.podspec
[Lottie iOS 4.4.0](https://github.com/airbnb/lottie-ios/pull/2252#issuecomment-1905052471) has been released. It includes the new privacy manifest file, and some other changes. I am bumping the package but i think since swift 5.6 is dropped, i would need to update the CI as well
> chore: bump lottie ios version

- packages/core/package.json
Looks like when moving over to v6 of the Lottie package it appears that the files were copied over to a new folder destination and there were changes to the `package.json` to limit the range of published files, unfortunately, it looks like these changes excluded the windows folder. So while [the files are present in the repo](https://github.com/lottie-react-native/lottie-react-native/tree/master/packages/core/windows), they are not published as part of the package, thus react native windows developers are effectively locked out of consuming the newer versions of this package.
- Fixed missing windows directly in published files list in the package.json
> [Windows]Add windows to lottie published files

- apps/fabric/ios/Podfile.lock
- apps/paper/ios/Podfile.lock
- packages/core/lottie-react-native.podspec
Bump the Lottie iOS version to the latest
> chore: bump lottie ios

- packages/core/src/LottieView/index.web.tsx
The inline require is no longer necessary now that the web implementation always uses `@dotlottie/react-player`.
Replacing it with an import simplifies typing in the file and surfaces dependency issues at compile-time.
- ran the `setup` and `paper:web` scripts after making the change and verified that the example app still works
> refactor(web): replace inline require with import

- apps/fabric/ios/Podfile.lock
- apps/paper/ios/Podfile.lock
- packages/core/lottie-react-native.podspec
Pin Pod spec version for iOS, due to Lottie-iOS 4.4.2 having a iOS 13 requirement (Which is not fully supported in all RN versions, only since 0.73) We will drop support for it once we decide the minimum RN support should be 0.73
> fix: pin lottie ios version in pod spec

- packages/core/package.json
Two different links lead to the same place on the npm registry page:
Update project homepage URL linking to old repository README in `package.json` to point to website highlighted in GitHub repository metadata.
> chore: update project homepage in package.json

- packages/core/src/LottieView/utils.ts
The check for whether a URL looks like a `.lottie` file was over-zealous and would trigger if the URL had `.lottie` anywhere in it, regardless of context. Make this more precise by parsing the URL and checking only the extension of the filename part.
> Fix incorrect .lottie URI path check

- packages/core/src/LottieView/utils.ts
Reverts lottie-react-native/lottie-react-native#1277 as URL is not implemented on Hermes
> Revert "Fix incorrect .lottie URI path check"

- packages/core/react-native.config.js
Removes legacy version check from `react-native.config.js`. 
The community CLI is no longer a dependency for React Native, meaning it may not be installed in every project. For example, projects that use Expo won't include the `@react-native-community/cli-*` packages. Consequently, this check will fail, leading to issues with autolinking components.
This version check can be removed safely, as the 9th version of the CLI was released two years ago. 
This change was tested using `expo` project on react native `0.76`.
> chore: Remove legacy version check in `react-native.config.js`

- packages/core/ios/Fabric/LottieAnimationViewComponentView.mm
Problem
In the Fabric architecture, updateProps calls each property’s setter individually, so the order of setters impacts behavior.
The issue occurs because setSpeed is called after setSourceJson (which initializes LottieAnimationView), affecting the onAnimationFinish callback:
In the new architecture: animationView?.play() is triggered immediately, but without a completion callback.
In the old architecture: playIfNeeded() is used, which includes a completion callback, ensuring onAnimationFinish is fired.
Solution Options
To ensure consistent behavior between the new and old architectures, two potential solutions were considered:
**_Option 1_**: Adjust the order of setter calls so the behaviour will be the same on both archs and make the onAnimationFinish callback in the new …
> Fix: Ensure onAnimationFinish Callback Fires Correctly in Fabric

- packages/core/android/src/main/AndroidManifest.xml
Been a very long time coming. Now that we only support 73 and above, we can safely get rid of this one
> fix: remove depracated property from AndroidManifest

- packages/core/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewPropertyManager.kt
- yarn.lock
We're making some changes in an upcoming react-native release which fix the nullability of some getters in ReadableNativeArray. This ensures that lottie-react-native will continue to build in the next RN release
> Fix nullability of getMap in LottieAnimationViewPropertyManager

- packages/core/package.json
closes #1356 
On ios on the new architecture, methods invoked on the view are being handled by the old arch manager. In order for the fabric files to be picked up correctly, the component provider needs to be defined in the codegen config in package.json.
Tested to work on both new and old arch
> fix: fix ios new arch by declaring component for codegen

- packages/core/ios/LottieReactNative/ContainerView.swift
Fixes an issue where a lottie view switching between a raw json (imported on the JS side) and a local asset (added to the iOS project) leads to the wrong animation being presented. The issue is only happening in the new architecture and on iOS only.
Upon inspection, when updateProps() is called, the local properties `sourceJson` and `sourceName` will not be updated properly and therefore when switching between the two formats, the old value in "sourceName" will still be set when a json animation is presented. When switching back, the check `newSourceName == sourceName` will equal to true and therefore the new animation won't be presented as it should.
The local properties don't seem to be used anywhere and can just create confusion/incorrect state when switching between different sources. …
> fix(ios): wrong animation when switching between raw json and string source in fabric

- packages/core/src/LottieView/index.tsx
the latest changes are breaking changes because now you are wrapping lottie view with a view
this change make the changes non-breaking for people who didn't use containerProps, so for those people if they was using LottieView normally without containerProps it will keep working as before.
> fix: bring backward compatibility for containerStyle prop
