lottie-react-native/lottie-react-native

README.md
package.json

Add installation docs

---

lib/js/Animation.js

Remove debugging console.log

---

lottie-react-native.podspec

I think this line was left over from the initial copy paste session :)

updated podspec summary

---

lib/js/Animation.js

Rename AirbnbLottieView -> LottieAnimationView 🐛

---

README.md

help-lazy-copy-paster

---

lib/ios/LottieReactNative/LRNContainerView.m

LAAnimationView was renamed to LOTAnimationView in lottie-ios at some point

Use LOTAnimationView instead of LAAnimationView

---

README.md

Also squashes trailing whitespace on line 4.

fix(README) correct file path for community gif

---

README.md

Add links to supported AE features

---

example/ios/Podfile.lock
lib/android/build.gradle
package.json

Upgrades lottie-ios and lottie-android

Minor tweeks for 1.1.x release

---

docs/api.md

Moving to a table for better readability, and expanding on how to handle animations with assets.
This should help devs understand how to use it, and should allow closing issues #80 and #145.

Update RN API doc

---

lib/android/build.gradle

Some nice improvements especially related to scaling have been added since the 2.2.0.

Bump lottie-android to 2.2.5

---

lib/android/src/main/java/com/airbnb/android/react/lottie/JSONReadableMap.java

keys method of JSONReadableMap implemented.

Iterators supported inside of the JSONReadableMap

---

src/ios/LottieReactNative/LRNContainerView.m
src/js/index.d.ts

Fixes https://github.com/airbnb/lottie-react-native/issues/299 and updates type declaration to include the `resizeMode` property.

Fix resizeMode for iOS and TypeScript

---

CHANGELOG.md
package.json

version bump 2.5.1

---

docs/api.md

Just found out about this, it should be documented, thanks.

Document play(startFrame, endFrame)

---

docs/api.md
src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java
src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewPropertyManager.java
src/js/LottieView.js
src/js/index.d.ts

As cacheStrategy property dependent on the animationName we need to use property manager pattern.
I decided to apply the pattern to all properties for android.
If you think this is too much I could roll back not related changes.
Ideally should wait for:
https://github.com/airbnb/lottie-android/pull/691
to be completed.

cacheStrategy property exposed to js layer.

---

docs/api.md
src/js/LottieView.js

Forgot to add it from [easy-lottie-react-native](https://github.com/bamlab/easy-lottie-react-native)

Add duration prop

---

src/ios/LottieReactNative.xcodeproj/project.pbxproj

When the project is linked by including the xcodeproj (not cocoapods) there is a build error in xcode 10.
```
/Users/janic/Developer/th3rdwave/app/node_modules/react-native/ReactCommon/fabric/graphics/platform/android/Float.h:8:10: 'limits' file not found
/Users/janic/Library/Developer/Xcode/DerivedData/th3rdwave-bpfvmasmymsqitghoxzryohjjlfr/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:8:9: While building module 'UIKit' imported from /Users/janic/Library/Developer/Xcode/DerivedData/th3rdwave-bpfvmasmymsqitghoxzryohjjlfr/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:9: While …
```

Cleanup framework / header search paths to fix xcode 10 build

---

src/js/index.d.ts

Adds typing for autoSize and enableMergePathsAndroidForKitKatAndAbove

---

README.md
docs/README.md
docs/typescript.md

Pretty simple and this commit shouldn't break anything.
Extended the documentation by adding a new file, linked to the main readme file.

Added documentation for typescript developers

---

docs/api.md
src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java
src/ios/LottieReactNative/LRNAnimationViewManager.m
src/ios/LottieReactNative/LRNContainerView.h
src/ios/LottieReactNative/LRNContainerView.m
src/js/LottieView.js
src/js/index.d.ts

Add callback function `onAnimationFinish` which will be called when animation is finished. Note that this callback will be called only when `loop` is set to false.

Add onAnimationFinish callback function

---

src/ios/LottieReactNative/LRNContainerView.h

Fixed typo that caused compilation failure

---

src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java

fixed compile error caused by previous pull request.

fix compile error

---

src/android/build.gradle

fix android need minSdk >= 26

---

.project
.settings/org.eclipse.buildship.core.prefs
src/android/build.gradle
src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java

Migrate bundle to androidX
| iOS     |    ✅❌     |
| Android |    ✅❌     |

[NEW] Update androidX

---

README.md

Replace android/app/src/main/java//MainApplication.java to android/app/src/main/java/<AppName>/MainApplication.java

[FIX] READ.me

---

.npmignore

The downloaded NPM package contains a few somewhat heavy gifs to not much benefit. This PR removes them and some other files not useful for production environments. 
`npm pack` and see that these files are omitted from the resulting tarball. 
N/A
`yarn add lottie-react-native && ls -la node_modules/lottie-react-native`

Make NPM package leaner

---

src/android/build.gradle

This significantly increases performance on Android by utilizing latest version of native library

Android performance improvement

---

README.md
lottie-react-native.podspec

Hi
I updated the podspec on my fork to use the last version of the pod lottie-ios (3.1.3)
fix #558

Fix podspec

---

README.md

[react-native-cli](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md) package by default allow us auto link any packages.
@emilioicai  thanks. Please review this PR 🎉 that's my first PR 🙌
| Android |    ✅   |
🙌Happy to contribute with your team🙌

docs || RN ==> 0.60 support autolinking

---

README.md

This PR adds a fastlane snippet to automatically account for embedding the Lottie.framework.

add auto embed fastlane

---

src/js/index.d.ts

This PR adds the testID prop to the AnimatedLottieView component typescript definition.
The testID prop is normally used to be able to grab a reference to a component while unit testing or end to end testing.
Before making the change:
After making the change:
- Use a LottieAnimatedView in a typescript file
- Add a testID prop to the LottieAnimatedView component
This change is on the typescript type definitions, so its platform independent.

Add testID prop to AnimatedLottieView typescript definition

---

src/js/index.d.ts

| iOS     |    ✅❌     |
| Android |    ✅❌     |
Closes #627

[WIP] Add animated interpolation type to progress

---

CHANGELOG.md
docs/api.md
src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java
src/ios/LottieReactNative/AnimationViewManagerModule.swift
src/ios/LottieReactNative/ContainerView.swift
src/ios/LottieReactNative/LRNAnimationViewManagerObjC.m
src/js/LottieView.js
src/js/index.d.ts

My team needed the ability to pause and resume animations from our RN project. I added two new commands. We also needed the position information, so I added an onLayout prop and exposed it.
I have these changes running in a build and they work as intended.
Get a ref to the LottieView and call pause/resume.
- [X ] I added the documentation in `README.md`
- [ X] I mentioned this change in `CHANGELOG.md`

Add Pause & Resume commands and OnLayout prop

---

src/js/LottieView.js

As we know, it's generally recommended that unnecessary re-rendering be avoided. So, unless it's a special case, Using PureComponent is a good idea.
This change is more useful for Lottie. That's because it is used where UI rendering occurs a lot.
None

Changed to PureComponent

---

example/android/app/build.gradle
src/android/build.gradle

Targeting at least version 29 is now required by Google Play

updating to target android sdk 30

---

docs/api.md

Add missing documentation for the argument sent in the onAnimationFinish callback.

Document onAnimationFinish isCancelled argument

---

lottie-react-native.podspec

See https://github.com/airbnb/lottie-ios/blob/master/lottie-ios.podspec#L28.

Fix tvos deployment_target to be compatible with the latest version of lottie-ios

---

README.md
packages/core/README.md

- Add `next` version in README and cleanup windows instructions
- Add README inside the `packages/core` for npm releases

docs: update readme

---

CHANGELOG.md
packages/core/package.json

- add missing condition ([bd44aff](https://github.com/react-native-community/lottie-react-native/commit/bd44aff93a8e5f992d1414ca9d839b850605eadf))
- old arch impl ([65ec453](https://github.com/react-native-community/lottie-react-native/commit/65ec453afa1663fcb564a21931af7f27531c106b))
- refactor event dispatch logic on android to fix fabric crash ([#1000](https://github.com/react-native-community/lottie-react-native/issues/1000)) ([ebb8006](https://github.com/react-native-community/lottie-react-native/commit/ebb8006da0385e44bb33817d44909376143a1695))
- implement native auto play for android ([63f71aa](https://github.com/react-native-community/lottie-react-native/commit/63f71aacbc007d8e2a9a1216ef2072023dc63fce))
- implement native auto play for ios …

chore: release 6.0.0-rc.3

---

packages/core/android/build.gradle

fix: fabric build on 0.68/0.69

---

apps/fabric/ios/Podfile.lock
apps/paper/ios/Podfile.lock
apps/paper/src/MemoryTest.tsx
packages/core/ios/LottieReactNative/ContainerView.swift

Fixes: https://github.com/lottie-react-native/lottie-react-native/issues/1010

fix: memory leak on iOS on deallocation

---

packages/core/android/build.gradle
packages/core/android/src/main/AndroidManifest.xml

Reference: https://github.com/react-native-community/discussions-and-proposals/issues/671

chore: add support for upcoming 0.73

---

packages/core/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewPropertyManager.kt

Keypaths were not being constructed properly. 
Fixes: https://github.com/lottie-react-native/lottie-react-native/issues/1040

fix: color filters on android

---

packages/core/ios/LottieReactNative/ContainerView.swift

- Fix bounding frame relative to parent view on iOS
- Cleanup fetch remote URL

fix(ios): animation bounding frame with parent view

---

apps/fabric/android/app/build.gradle
apps/fabric/android/app/src/debug/java/com/airbnb/android/lottie/rnexamplefabric/ReactNativeFlipper.java
apps/fabric/android/app/src/main/java/com/airbnb/android/lottie/rnexamplefabric/MainActivity.java
apps/fabric/android/app/src/main/java/com/airbnb/android/lottie/rnexamplefabric/MainApplication.java
apps/fabric/android/app/src/main/res/values/strings.xml
apps/fabric/android/app/src/release/java/com/airbnb/android/lottie/rnexample/ReactNativeFlipper.java
packages/core/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManagerImpl.kt
packages/core/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewPropertyManager.kt
packages/core/android/src/newarch/com/airbnb/android/react/lottie/LottieAnimationViewManager.kt
packages/core/android/src/oldarch/com/airbnb/android/react/lottie/LottieAnimationViewManager.kt

Related to: https://github.com/lottie-react-native/lottie-react-native/pull/1071

feat: dotLottie support for android

---

.github/workflows/android-build.yml
apps/fabric/package.json
apps/paper/package.json
package.json
packages/core/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewPropertyManager.kt

Fixes #1105 
Post Mortem:
- Added CI for catching build errors on Android

fix: android build issue

---

.github/workflows/ios-fabric-build.yml

chore(ci): fix ios-fabric-build.yml

---

MIGRATION-5-TO-6.md
README.md

Add documentation describing the changes from V5 to V6 and how to handle the change

chore: update documentation to include a new migration doc from V5 to V6

---

.github/workflows/ios-paper-build.yml
apps/fabric/Gemfile
apps/fabric/Gemfile.lock
apps/fabric/android/app/src/main/java/com/airbnb/android/lottie/rnexamplefabric/MainApplication.kt
apps/fabric/ios/Podfile.lock
apps/fabric/ios/example.xcodeproj/project.pbxproj
apps/fabric/package.json
apps/paper/Gemfile
apps/paper/Gemfile.lock
apps/paper/ios/Podfile.lock
apps/paper/ios/example.xcodeproj/project.pbxproj
apps/paper/package.json
yarn.lock

The CI is broken because Cocoapods 1.15 came out and ruined everyone's day. This PR brings the CI back into working condition so i can wrap up Bridgeless

fix: update RN to fix the pipeline

---

MIGRATION-5-TO-6.md

Add mentions of the new render prop and what it can do

chore: Update MIGRATION-5-TO-6.md

---

packages/core/src/LottieView/index.web.tsx

fixes https://github.com/lottie-react-native/lottie-react-native/issues/1195

Improve web consistency with native

---

packages/core/lottie-react-native.podspec

fix: Add Xcode 16 beta support

---

example/App.tsx
packages/core/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManagerImpl.kt
packages/core/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewPropertyManager.kt
packages/core/android/src/newarch/com/airbnb/android/react/lottie/LottieAnimationViewManager.kt
packages/core/android/src/oldarch/com/airbnb/android/react/lottie/LottieAnimationViewManager.kt
packages/core/src/LottieView/index.tsx
packages/core/src/specs/LottieAnimationViewNativeComponent.ts
packages/core/src/types.ts

Addresses https://github.com/lottie-react-native/lottie-react-native/issues/1258

feat: add enable safe mode prop on Android

---

example/App.tsx
packages/core/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManagerImpl.kt

Closes #1303 
Aligns Android's play behaviour with iOS'

fix: play lottie animation without restarting, similar to iOS

---

packages/core/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewPropertyManager.kt

When the application uses OTA to deliver updates, the dotlottie assets can't be loaded on android.
Let's say that a dotlottie asset is located in the src/assets/animations folder.
Scenario 1 - No OTA update is installed on the application
When we are passing this file as source to the LottieView, Android layer of this lib uses following uri to set it as dotLottieSourceUri `src_assets_animations_myanimation`. Lottie can load this file as expected.
Scenario 2 - A irrelevant OTA update is pushed and installed on the device
The same file, which we used above is now passed to the android layer with following uri
`file:///data/user/0/com.example.app/files/output/raw/src_assets_animations_myanimation.lottie`
Unfortunately the current logic can't handle any URI which has file:// protocol in it. …

feat(android): support locally stored dotlottie assets  
